"""Turn uploaded chat exports into plain text blocks.

Supported: .txt, .md, .json (ChatGPT `conversations.json` or simple lists),
.html (ChatGPT `chat.html` or any HTML page) and .pdf (text layer only).

For ChatGPT exports only messages written by the user are kept; assistant
replies were generated by an AI and could contain invented details
(docs/ARCHITECTURE.md, D11). The raw upload is never stored.
"""
from __future__ import annotations

import io
import json
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from html.parser import HTMLParser

SUPPORTED = {"txt", "md", "json", "html", "htm", "pdf"}
MAX_PDF_PAGES = 400


class ParseError(ValueError):
    pass


@dataclass
class SourceText:
    text: str
    written_on: str = ""  # when the message was typed (NOT when the event happened)
    origin: str = ""  # e.g. conversation title


def decode(raw: bytes) -> str:
    if raw.startswith((b"\xff\xfe", b"\xfe\xff")):
        return raw.decode("utf-16")
    try:
        return raw.decode("utf-8-sig")
    except UnicodeDecodeError:
        return raw.decode("latin-1")


def _ts(value) -> str:
    try:
        return datetime.fromtimestamp(float(value), tz=timezone.utc).date().isoformat()
    except (TypeError, ValueError, OverflowError, OSError):
        return ""


def _parts_text(content) -> str:
    if not isinstance(content, dict):
        return str(content or "")
    parts = content.get("parts")
    if isinstance(parts, list):
        return "\n".join(p for p in parts if isinstance(p, str))
    return str(content.get("text") or "")


def _chatgpt_conversations(data: list) -> list[SourceText]:
    out: list[SourceText] = []
    for convo in data:
        mapping = convo.get("mapping") or {}
        title = str(convo.get("title") or "")[:120]
        nodes = []
        for node in mapping.values():
            msg = (node or {}).get("message") or {}
            role = ((msg.get("author") or {}).get("role")) or ""
            if role != "user":
                continue
            text = _parts_text(msg.get("content")).strip()
            if text:
                nodes.append((msg.get("create_time") or 0, text))
        for created, text in sorted(nodes, key=lambda n: n[0] or 0):
            out.append(SourceText(text=text, written_on=_ts(created), origin=title))
    return out


def _generic_json(data) -> list[SourceText]:
    """Accept [{"date": "...", "text": "..."}], {"messages": [...]} or a list of strings."""
    if isinstance(data, dict):
        for key in ("messages", "entries", "items", "conversations"):
            if isinstance(data.get(key), list):
                return _generic_json(data[key])
        return [SourceText(text=json.dumps(data, ensure_ascii=False))]
    out: list[SourceText] = []
    for item in data if isinstance(data, list) else []:
        if isinstance(item, str):
            out.append(SourceText(text=item))
        elif isinstance(item, dict):
            role = str(item.get("role") or item.get("author") or "user").lower()
            if role in ("assistant", "system", "tool"):
                continue
            text = item.get("text") or item.get("content") or item.get("message") or ""
            if isinstance(text, dict):
                text = _parts_text(text)
            date = str(item.get("date") or "")
            # An explicit "date" on an entry describes the entry itself, so it is kept in the text.
            prefix = f"{date}\n" if date else ""
            if str(text).strip():
                out.append(SourceText(text=prefix + str(text)))
    return out


def parse_json(text: str) -> list[SourceText]:
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        raise ParseError("The JSON file could not be read.") from exc
    if isinstance(data, list) and data and isinstance(data[0], dict) and "mapping" in data[0]:
        return _chatgpt_conversations(data)
    return _generic_json(data)


class _TextExtractor(HTMLParser):
    BLOCK = {"p", "div", "br", "li", "h1", "h2", "h3", "h4", "h5", "h6", "tr", "section", "article"}

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.parts: list[str] = []
        self._skip = 0

    def handle_starttag(self, tag, attrs):
        if tag in ("script", "style", "noscript"):
            self._skip += 1
        elif tag in self.BLOCK:
            self.parts.append("\n")

    def handle_endtag(self, tag):
        if tag in ("script", "style", "noscript") and self._skip:
            self._skip -= 1
        elif tag in self.BLOCK:
            self.parts.append("\n")

    def handle_data(self, data):
        if not self._skip:
            self.parts.append(data)


JSON_DATA_RE = re.compile(r"var\s+jsonData\s*=\s*(\[.*?\]);\s*\n", re.S)


def parse_html(text: str) -> list[SourceText]:
    match = JSON_DATA_RE.search(text)
    if match:
        try:
            return parse_json(match.group(1))
        except ParseError:
            pass
    extractor = _TextExtractor()
    extractor.feed(text)
    return [SourceText(text=re.sub(r"\n{3,}", "\n\n", "".join(extractor.parts)).strip())]


def parse_pdf(raw: bytes) -> list[SourceText]:
    try:
        from pypdf import PdfReader
    except ImportError as exc:  # pragma: no cover
        raise ParseError("PDF support needs the 'pypdf' package.") from exc
    try:
        reader = PdfReader(io.BytesIO(raw))
        if reader.is_encrypted:
            raise ParseError("Encrypted PDFs are not supported.")
        pages = [page.extract_text() or "" for page in reader.pages[:MAX_PDF_PAGES]]
    except ParseError:
        raise
    except Exception as exc:
        raise ParseError("The PDF could not be read.") from exc
    text = "\n\n".join(pages).strip()
    if not text:
        raise ParseError("No text was found in the PDF (scanned PDFs are not supported).")
    return [SourceText(text=text)]


def parse_upload(filename: str, raw: bytes) -> tuple[str, list[SourceText]]:
    ext = filename.rsplit(".", 1)[-1].lower() if "." in filename else ""
    if ext not in SUPPORTED:
        raise ParseError("Supported files: .txt, .md, .json, .html and .pdf.")
    if ext == "pdf":
        if not raw.startswith(b"%PDF"):
            raise ParseError("The file is not a valid PDF.")
        return ext, parse_pdf(raw)
    text = decode(raw)
    if "\x00" in text:
        raise ParseError("The file does not look like text.")
    if ext == "json":
        return ext, parse_json(text)
    if ext in ("html", "htm"):
        return "html", parse_html(text)
    return ext, [SourceText(text=text)]
